server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/movies/**
            - id: consumer-service
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/api/bookings/**,/api/booking-seats/**,/api/tickets**
            - id: show-service
              uri: lb://SHOW-SERVICE
              predicates:
                - Path=/api/shows/**
            - id: theatre-service
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/api/bookings/**,/api/screens/**,/api/seats/**,/api/theatres/**
            - id: admmin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/theatre-approval-requests/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
