server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:

            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/movies/**

            - id: consumer-service
              uri: lb://CONSUMER-SERVICE
              predicates:
                - Path=/api/bookings/**,/api/booking-seats/**,/api/tickets/**

            - id: show-service
              uri: lb://SHOW-SERVICE
              predicates:
                - Path=/api/shows/**

            - id: theatre-service
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/api/screens/**,/api/seats/**,/api/theatres/**,/api/owner/**

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/theatre-approval-requests/**,/api/role-approval-requests/**

            - id: auth-service-public
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: auth-service-protected
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/user/**

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: tickebook_auth_jwt_super_secure_secret_2026_value